[tool.poetry]
name = "MOBI_QC"
version = "0.1.0"
description = "mobi qc"
authors = ["Bryan Gonzalez <bryan.gonzalez@childmind.org>",
"Apurva Goekhe <apurva.goekhe@hildmind.org>",
"Camilla Strauss <camilla.strauss@childmind.org",
"Adam Santorelli <adam.santorelli@childmind.org>"
]
license = "GNU Lesser General Public License v3.0"
readme = "README.md"
packages = [{include = "MOBI_QC", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.11, <3.14"
pandas = "^2.3.3"
pyxdf = "^1.17.0"
numpy = "^2.3.5"
pylsl = "^1.17.6"



[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
mypy = "^1.15.0"
pre-commit = "^4.2.0"
pytest-cov = "^7.0.0"
ruff = "^0.14.2"


[tool.poetry.group.docs.dependencies]
pdoc = "^15.0.1"

[tool.pytest.ini_options]
pythonpath = [
  "src"
]
testpaths = [
  "tests"
]

[tool.mypy]
ignore_missing_imports = true

[tool.ruff]
line-length = 120
indent-width = 4
src = ["src"]
target-version = "py311"

[tool.ruff.lint]
select = ["ANN", "D", "E", "F", "I"]
ignore = [
  "ANN101",  # self should not be annotated.
  "ANN102"  # cls should not be annotated.
]
fixable = ["ALL"]
unfixable = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = []

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"